# vim: set expandtab shiftwidth=2 tabstop=8 textwidth=0:
#
# This is a bit complicated because GitLab only allows one script: per job
# but we have a bunch of commands we want to re-run for each build. YAML
# doesn't have anything to append to arrays with templates.
#
# We could just define everything as separate job but that would require 
# pulling docker images && dnf update on every job. That's slow and heavy.
#
# So instead we use BUILDSTRING as the main builder and pass what we need through
# shell variables. The only two that matter:
#
# MESON_PARAMS=-Denable-something=true
# NINJA_ARGS=dist 

variables:
  MESON_BUILDDIR: builddir
  NINJA_ARGS: ''
  MESON_PARAMS: ''
  RPMS: 'git gcc gcc-c++ meson check-devel libudev-devel libevdev-devel doxygen graphviz valgrind binutils libwacom-devel cairo-devel gtk3-devel glib2-devel mtdev-devel'

stages:
  - initial
  - next

.defaults: &defaults
  artifacts:
    name: "meson-logs-$CI_JOB_NAME"
    when: always
    expire_in: 1 week
    paths:
      - $MESON_BUILDDIR/meson-logs

.fedora_install_from_cache: &fedora_install_from_cache
  stage: next
  before_script:
    - dnf install -y rpm_cache/*
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - rpm_cache/
    policy: pull

.fedora_install: &fedora_install
  before_script:
    - dnf upgrade -y
    - dnf install -y $RPMS

.default_build: &default_build
  <<: *defaults
  script:
    - rm -rf $MESON_BUILDDIR
    - meson $MESON_BUILDDIR $MESON_PARAMS
    - meson configure $MESON_BUILDDIR
    - ninja -C $MESON_BUILDDIR $NINJA_ARGS

fedora_latest_prep_cache:
  stage: initial
  image: fedora:latest
  script:
    - dnf update -y --downloadonly --downloaddir rpm_cache
    - dnf install -y --downloadonly --downloaddir rpm_cache $RPMS
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    policy: push
    paths:
      - rpm_cache/

build-standard:
  image: fedora:latest
  <<: *defaults
  <<: *fedora_install_from_cache
  <<: *default_build

build-nowacom:
  image: fedora:latest
  variables:
    MESON_PARAMS: '-Dlibwacom=false'
  <<: *defaults
  <<: *fedora_install_from_cache
  <<: *default_build

build-nodoc:
  image: fedora:latest
  variables:
    MESON_PARAMS: '-Ddocumentation=false'
  <<: *defaults
  <<: *fedora_install_from_cache
  <<: *default_build

build-nogui:
  image: fedora:latest
  variables:
    MESON_PARAMS: '-Ddebug-gui=false'
  <<: *defaults
  <<: *fedora_install_from_cache
  <<: *default_build

build-notests:
  image: fedora:latest
  variables:
    MESON_PARAMS: '-Dtests=false'
  <<: *defaults
  <<: *fedora_install_from_cache
  <<: *default_build

fedora-27:
  stage: initial
  image: fedora:27
  <<: *defaults
  <<: *fedora_install
  <<: *default_build

